version: '3.7'
services:
  postgres:
      image: postgres:16.2-alpine3.19
      container_name: laravel-database
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_DATABASE}
